name: Install drtpy using pipx (Ubuntu)

on:
  pull_request:
    branches: [main, feat/*]
  workflow_dispatch:

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  install:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pipx
        run: |
          sudo apt update
          sudo apt install pipx
          pipx ensurepath
      - name: Install drtpy
        run: |
          pipx install git+https://github.com/TerraDharitri/drt-py-sdk-cli@$BRANCH_NAME
      - name: Smoke test
        run: |
          drtpy --version
